# completion.py
"""
Tab completion for zsh and bash.

Both scripts are generated from the same command list as `docky help`
(passed in by docky.py), so a new command or flag shows up in
completion without anyone remembering to edit a shell script. Project
and service names are completed live via the hidden `docky __complete`.

The scripts are written next to the code (completions/docky.zsh and
completions/docky.bash) and sourced from the end of ~/.zshrc / ~/.bashrc
-- after Oh My Zsh or any other compinit -- so opening a shell never runs
Python. `docky self-update` regenerates them.
"""
import os
from pathlib import Path

INSTALL_DIR = Path(__file__).resolve().parent
COMPLETION_DIR = INSTALL_DIR / "completions"
MARKER = "# Docky tab completion"

# What a positional argument completes to.
PROJECTS = "project"
PROJECTS_OR_ALL = "project_or_all"
SERVICES = "service"
SHELLS = "shell"

def _zsh_quote(text):
    return "'" + text.replace("'", "'\\''") + "'"

def _arms(spec, aliases):
    """[(case pattern, flags, [arg kinds])] -- one per command, aliases folded in."""
    arms = []
    for name, entry in spec.items():
        names = [name] + [a for a, target in aliases.items() if target == name]
        arms.append(("|".join(names), entry.get("flags", []), entry.get("args", [])))
    return arms

def zsh_script(commands, spec, aliases):
    """commands: [(name, description)]; spec: {name: {"args": [...], "flags": [...]}}."""
    described = "\n".join(f"    {_zsh_quote(name.replace(':', chr(92) + ':') + ':' + desc)}" for name, desc in commands)
    flag_cases, arg_cases = [], []
    for pattern, flags, args in _arms(spec, aliases):
        if flags:
            flag_cases.append(f"    {pattern}) flags=({' '.join(flags)}) ;;")
        for pos, kind in enumerate(args):
            for name in pattern.split("|"):
                if kind == PROJECTS:
                    arg_cases.append(f'    {name}:{pos}) _docky_values projects ;;')
                elif kind == PROJECTS_OR_ALL:
                    arg_cases.append(f'    {name}:{pos}) compadd -- all; _docky_values projects ;;')
                elif kind == SERVICES:
                    arg_cases.append(f'    {name}:{pos}) _docky_values services "${{words[3]}}" ;;')
                elif kind == SHELLS:
                    arg_cases.append(f'    {name}:{pos}) compadd -- zsh bash ;;')
    return f"""#compdef docky
# Docky tab completion for zsh. Generated by `docky completion zsh`;
# `docky self-update` regenerates it, so edits here don't last.

(( $+functions[compdef] )) || {{ autoload -Uz compinit && compinit -i; }}

_docky_values() {{
  local -a values
  values=(${{(f)"$(command docky __complete "$@" 2>/dev/null)"}})
  (( ${{#values}} )) && compadd -- $values
}}

_docky() {{
  local -a cmds flags
  cmds=(
{described}
  )
  if (( CURRENT == 2 )); then
    _describe -t commands 'docky command' cmds
    return
  fi

  local cmd=${{words[2]}} cur=${{words[CURRENT]}}
  case $cmd in
{chr(10).join(flag_cases) or "    *) ;;"}
  esac
  if [[ $cur == -* ]]; then
    (( ${{#flags}} )) && compadd -- $flags
    return
  fi
  # A target can also be a folder path.
  if [[ $cur == [/~.]* ]]; then
    _files -/
    return
  fi

  # Which positional argument is being completed (flags don't count)?
  local -i pos=0 i
  for (( i = 3; i < CURRENT; i++ )); do
    [[ ${{words[i]}} == -* ]] || (( pos++ ))
  done
  case "$cmd:$pos" in
{chr(10).join(arg_cases) or "    *) ;;"}
    *) (( ${{#flags}} )) && compadd -- $flags ;;
  esac
}}

compdef _docky docky
"""

def bash_script(commands, spec, aliases):
    names = " ".join(name for name, _ in commands)
    flag_cases, arg_cases = [], []
    for pattern, flags, args in _arms(spec, aliases):
        if flags:
            flag_cases.append(f"    {pattern}) flags=\"{' '.join(flags)}\" ;;")
        for pos, kind in enumerate(args):
            for name in pattern.split("|"):
                if kind == PROJECTS:
                    arg_cases.append(f'    {name}:{pos}) words=$(command docky __complete projects 2>/dev/null) ;;')
                elif kind == PROJECTS_OR_ALL:
                    arg_cases.append(f'    {name}:{pos}) words="all $(command docky __complete projects 2>/dev/null)" ;;')
                elif kind == SERVICES:
                    arg_cases.append(f'    {name}:{pos}) words=$(command docky __complete services "${{COMP_WORDS[2]}}" 2>/dev/null) ;;')
                elif kind == SHELLS:
                    arg_cases.append(f'    {name}:{pos}) words="zsh bash" ;;')
    return f"""# Docky tab completion for bash. Generated by `docky completion bash`;
# `docky self-update` regenerates it, so edits here don't last.

_docky() {{
  local cur="${{COMP_WORDS[COMP_CWORD]}}"
  COMPREPLY=()
  if [ "$COMP_CWORD" -eq 1 ]; then
    COMPREPLY=( $(compgen -W "{names}" -- "$cur") )
    return
  fi

  local cmd="${{COMP_WORDS[1]}}" flags="" words=""
  case "$cmd" in
{chr(10).join(flag_cases) or "    *) ;;"}
  esac
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "$flags" -- "$cur") )
    return
  fi
  # A target can also be a folder path.
  if [[ "$cur" == /* || "$cur" == "~"* || "$cur" == .* ]]; then
    COMPREPLY=( $(compgen -d -- "$cur") )
    return
  fi

  # Which positional argument is being completed (flags don't count)?
  local pos=0 i
  for (( i = 2; i < COMP_CWORD; i++ )); do
    [[ "${{COMP_WORDS[i]}}" == -* ]] || pos=$((pos + 1))
  done
  case "$cmd:$pos" in
{chr(10).join(arg_cases) or "    *) ;;"}
    *) words="$flags" ;;
  esac
  COMPREPLY=( $(compgen -W "$words" -- "$cur") )
}}

complete -F _docky docky
"""

def write_scripts(commands, spec, aliases):
    COMPLETION_DIR.mkdir(exist_ok=True)
    (COMPLETION_DIR / "docky.zsh").write_text(zsh_script(commands, spec, aliases))
    (COMPLETION_DIR / "docky.bash").write_text(bash_script(commands, spec, aliases))

def rc_targets():
    """[(shell, rc file)]: the login shell's rc, plus the other one if it already exists."""
    login = os.path.basename(os.environ.get("SHELL", ""))
    home = Path.home()
    targets = []
    for shell, rc in (("zsh", home / ".zshrc"), ("bash", home / ".bashrc")):
        if shell == login or rc.exists():
            targets.append((shell, rc))
    return targets

def source_line(shell):
    script = COMPLETION_DIR / f"docky.{shell}"
    return f'[ -f "{script}" ] && . "{script}"'

def install(commands, spec, aliases, modify_rc=True):
    """
    Write both scripts and hook them into the user's shell rc files.
    Returns [(rc, status)] with status "added", "present" or "skipped".
    Only appends -- never rewrites the rest of the file.
    """
    write_scripts(commands, spec, aliases)
    results = []
    for shell, rc in rc_targets():
        line = source_line(shell)
        try:
            text = rc.read_text() if rc.exists() else ""
        except OSError:
            results.append((rc, "skipped"))
            continue
        if line in text:
            results.append((rc, "present"))
        elif not modify_rc:
            results.append((rc, "skipped"))
        else:
            try:
                with rc.open("a") as f:
                    f.write(f"{'' if text.endswith(chr(10)) or not text else chr(10)}\n{MARKER} (added by Docky; remove both lines to turn it off)\n{line}\n")
                results.append((rc, "added"))
            except OSError:
                results.append((rc, "skipped"))
    return results
